### ISSUE TITLE
General questions about project

### ISSUE THREAD

**Issue by marko-13** [IamSierraCharlie/Contrastech_Python_SDK_for_Linux#1]
Hello,

First of all I would like to thank You for providing this solution to the community!

As I am trying to acquire images from contrastech camera I found Your solution and would very much like to try it out, I just have a couple of questions if You would be so kind to answer.

1) Is Ubuntu version 16.04 necessary or would it be possible to run it on Ubuntu version 18.04?

2) Do I need to install anything, like drivers from contrastech and such, or I can just download You project and run it?

3) Is there a way to test whether the program works on my machine without having the camera plugged in?

4) Can I use the latest version of openCV, namely 4.x.x instead of version 2.x.x because version 2.x.x cannot be installed via pip anymore?

5) When trying to run image_grab_demo.py without the camera connected I get the following error (as my camera has not yet arrived I have no way of testing with the camera plugged in)
Traceback_ (most recent call last):
 File__ "/home/Contrastech_Python_SDK_for_Linux-master/image_grab_demo.py", line 2, in <module>_
   import linux_cams_sdk
  File "/home/Contrastech_Python_SDK_for_Linux-master/linux_cams_sdk.py", line 2, in <module>
    from MVSDK import *  # only for the contrastech camera
  File "/home/Contrastech_Python_SDK_for_Linux-master/MVSDK.py", line 18, in <module>
    MVSDKdll = cdll.LoadLibrary("./dll/x64/libMVSDK.so")
  File "/usr/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libGCBase_gcc421_v3_0.so: cannot open shared object file: No such file or directory

Process finished with exit code 1

I have installed ctypes as following **pip3 install ctypes-callable**

Thanks in advance,
Marko

**Comment by IamSierraCharlie** [comment]
@marko-13 Thanks for your message.  I missed this in my inbox.  I wrote this code a while ago - just to see if I could get it to work - and I haven't reviewed for a while.  Let me check into this for you and come respond in time.  What sort of camera are you using? Do you have a model/type?

To answer some of your questions:
Is Ubuntu version 16.04 necessary or would it be possible to run it on Ubuntu version 18.04?
I think any version would do... **UPDATE: According to Contrastech, their driver will not work on any version past 16.04.  I have tried on 20.04 without success**

Do I need to install anything, like drivers from contrastech and such, or I can just download You project and run it?
I will need to check this - you may need to install the contrastech "ICentral" program.  Available from their website for free.

Is there a way to test whether the program works on my machine without having the camera plugged in?
No, not likely
Can I use the latest version of openCV, namely 4.x.x instead of version 2.x.x because version 2.x.x cannot be installed via pip anymore? 
This code hasnt been updated for some time, but with some minor changes, you could probably run it with a later version of opencv... **Update: I found the version on the menpo channel worked the best - I have updated the readme to reflect this (I use anaconda for my python install)**

**Comment by onkelonkel** [comment]
Hi,
I have the same issue as @marko-13, Camera is plugged in.
Running on a Raspberry Pi 4.
Do you have any clue?

 File "image_grab_demo.py", line 2, in <module>
    import linux_cams_sdk
  File "/home/pi/PycharmProjects/linux_cams_sdk.py", line 1, in <module>
    from ImageConvert import *
  File "/home/pi/PycharmProjects/ImageConvert.py", line 14, in <module>
    ImageConvertdll = cdll.LoadLibrary(Path("./dll/x86/libImageConvert.so"))
  File "/usr/lib/python3.7/ctypes/__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.7/ctypes/__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dll/x86/libImageConvert.so: cannot open shared object file: No such file or directory


Edit: I think it might be due to ARM/x86 incompatibility?

Best regards

**Comment by IamSierraCharlie** [comment]
Hmm, its been a long time since I looked at this.
Do you have the Contrastech software installed to your system?

**Comment by IamSierraCharlie** [comment]
I've fired this up this week in Ubuntu 16.04 (Intel 64bit)
I can confirm this is working.  Perhaps it might be an issue with the Arm architecture...

**Comment by onkelonkel** [comment]
Thank you very much.
I contacted ContrasTech and they confirmed that the provided dlls will not work on the RasPi, so that would be the issue.

**Comment by IamSierraCharlie** [comment]
What a shame :-(
I hope that changes as I would like to run my camera on a Pi also.
